language: ruby
rvm:
  - 2.0.0
before_install:
  - sudo apt-get update -qq
  - sudo apt-get install -qq qt4-qmake
  - sudo apt-get install -qq xvfb
  - export DISPLAY=:99.0
  - sh -e /etc/init.d/xvfb start

before_script:
  - psql -c 'create database courtfinder_test;' -U postgres
services: postgres
script:
  - bundle exec rake db:migrate
  - bundle exec rake spec
env:
  - TRAVIS=true
